"""
Django settings for crud project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'bg4a-jm$@jn0@*ikuf7$s21#0+2e1bor_1)mg%*o4=d^+^%#n&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # locla apps
    'articles.apps.ArticlesConfig',
    'jobs.apps.JobsConfig',
    # thrtd-party libraries
    'imagekit',
    # django apps
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'crud', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#실제 파일이나 디렉토리가 아니고, URL로만 존재하는 단위.
STATIC_URL = '/static/'
# app/static/ 의 경로로 작동한다.
#개발 단계에서 사용하는 실제 정적 파일이 위치한 경로를 저장하는 설정.
#보통 boot strap, 외부 템플릿 등을 저장하기 위해 사용함.

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'crud', 'assets'),
]
# static을 로드할 때 project의 assets의 폴더에서 경로를 지정한다.

#STATIC_URL 와 비슷한 역할을 한다.
# 업로드 된 파일의 URL 주소를 만들어주는 역할.
# STATIC_URL 과 값이 달라야한다.
MEDIA_URL = '/media/'

# STATICFILES_DIRS 와 비슷한 역할을 한다.
# 실제 파일이 업로드 되면 어디에 저장될지 정하는 실제 경로
# STATICFILES_DIRS와 값이 달라야한다.
# 개발 단계에서 사용하는 경로이므로, 실제 배보 단계에서는 다른 경로를 설정을 해야 한다.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')